version: '3.8'

services:
  buscaminas_db:
    container_name: buscaminas_db
    image: "postgres:13"
    ports: 
      - "5432:5432"
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - buscaminas_data:/var/lib/postgresql/data

volumes: 
  buscaminas_data: {}
